// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchForWebsites(arg1:string,arg2:string,arg3:boolean):Promise<Array<string>>;

export function TakeScreenshotOfWebsite(arg1:string,arg2:boolean):Promise<string>;
