// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCurrentJob() {
  return window['go']['main']['App']['CancelCurrentJob']();
}

export function GetScreenshotBase64(arg1) {
  return window['go']['main']['App']['GetScreenshotBase64'](arg1);
}

export function GetScreenshotFilenames() {
  return window['go']['main']['App']['GetScreenshotFilenames']();
}

export function ResetScreenshotsDir() {
  return window['go']['main']['App']['ResetScreenshotsDir']();
}

export function SearchForWebsites(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchForWebsites'](arg1, arg2, arg3);
}

export function TakeScreenshotOfWebsite(arg1, arg2) {
  return window['go']['main']['App']['TakeScreenshotOfWebsite'](arg1, arg2);
}

export function WriteBusinessUrlToExcelDatabase(arg1) {
  return window['go']['main']['App']['WriteBusinessUrlToExcelDatabase'](arg1);
}
