// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchForWebsites(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchForWebsites'](arg1, arg2, arg3);
}

export function TakeScreenshotOfWebsite(arg1, arg2) {
  return window['go']['main']['App']['TakeScreenshotOfWebsite'](arg1, arg2);
}
